bravo:
  host:
    url: localhost
    port: 8188
    kafka: "localhost:9092"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: camunda
    password: camunda
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8181
